### ISSUE TITLE
Asserting JSON responses

### ISSUE THREAD

**Issue by Rashadse** [aviaviavi/curl-runnings#44]
https://github.com/aviaviavi/curl-runnings/blob/9f08b25232c28c437454614c989659602cbfa18e/examples/interpolation-spec.yaml#L2

Hi, i am wondering if this would work with JSON files and not only yaml files? We are wondering if this project was intended to work with large data intensive APIs and the idea is we want to include larger json objects from other files and assert that they match the response body data. Our responses might be several hundred lines of json, and we cannot specify that in the case.yml or case.json files.

**Comment by aviaviavi** [comment]
Hi @Rashadse, importing data into your spec is just a yaml feature at this point, since we get this functionality from an external yaml parsing dependency. There are many tools out there that can convert json into yaml, so I think this limitation could be worked around without too much effort.

As for the intention for working with large payloads - while this was not an explicit goal of the project, I expect curl-runnings to work fine with large objects. There could likely be some improvements to make to the error outputs for extremely large payloads. I'd be happy to make changes to fit your use-case if you end up having specific requests.

**Comment by aviaviavi** [comment]
@Rashadse let me know if using a yaml converter outside the scope of curl-runnings isn't suitable for you. I'm open to trying to come up with a solution but I'd be curious to know what issues you ran into.

**Comment by Rashadse** [comment]
@aviaviavi hi again, thank you for replying and for your optimism. We're looking at yaml converters right now we did not run up into an issue but we were speculating whether this project would work with us or not. We decided to invest some time in trying your project along with a yaml converter.
Would you like us to keep you updated on this issue or should we close it and update somewhere else?

**Comment by aviaviavi** [comment]
Glad to hear you're giving it a try! Yes please keep me posted on how things are going. I'll close this issue for now, but feel free to open up more if anything pops up.
